### ISSUE TITLE
Add CodeCoverage Report

### ISSUE THREAD

**Issue by koeeenig** [icarus-consulting/Yaapii.Xambly#102]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
Code coverage report is generated on build.

### Actual Behavior

No report exists

**Comment by icaOBU** [comment]
Getting the eroor after step "commiting":
```
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

**Comment by Meerownymous** [comment]
@icaOBU please checl te settings for generating the pdb file. This is in the project settings in visual studio, or in the csproj file. Pdb generator must be set to „full“ to work properly with opencover.

**Comment by icaOBU** [comment]
setted debug-information to full. It don´t fix the problem...

**Comment by Meerownymous** [comment]
you can further investigate the xml which opencover has created. There is for every assembly a xml block, and there is a reason which tells you, why it has been skipped. Maybe the assembly is not present, but maybe it is present and has been skipped for some reason.
