### ISSUE TITLE
Selecting root with Xpath directive does not work

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Xambly#103]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
I can add a child by selecting the root using this:
```new Directives().Add("root").Add("child").Xpath("/").Attr("some","attribute")```

### Actual Behavior
Exception is thrown:

```
Yaapii.Xml.Xambly.ImpossibleModificationException : Exception at dir 4: ATTR 'name', 'repo-2.xml' (Unable to cast object of type 'System.Xml.XmlDocument' to type 'System.Xml.XmlElement'.)
```

**Comment by aveXcaesar** [comment]
@Meerownymous 
The exception is correct.
If you enter the XPath `/` you get the document node.
What you want to select the root element. To select it you have to use `/*` or `/root`

See examples at the end: https://de.wikipedia.org/wiki/XPath
Or here (Path Expression): https://www.w3schools.com/xml/xpath_syntax.asp
or try it out with an online XPath tester
