### ISSUE TITLE
Package is published with incorrect Name

### ISSUE THREAD

**Issue by koeeenig** [icarus-consulting/Yaapii.Xambly#107]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior

Package is listed on Nuget.org as Yaapii.Xambly

### Actual Behavior

The Package is listed on nuget.org as Yaapii.Xml.Xambly

**Comment by icaOBU** [comment]
Potential fix through #117

**Comment by koeeenig** [comment]
fixed
