### ISSUE TITLE
CopyOf Class does not work with XmlDocument

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Xambly#114]
### Expected Behavior
XmlDoument is a XmlNode, so CopyOf should be able to handle.

### Actual Behavior
CopyOf throws exception

### Steps to reproduce the behavior
See `Yaapii.Xml.Xambly.Tests.DirectiveCopyOfXmlDocument()`

### The log given by the failure.
Message: System.NullReferenceException : Object reference not set to an instance of an object. (Attributes Propertie)

### Mention any other details that might be useful
https://github.com/icarus-consulting/Yaapii.Xambly/tree/i114-CopyOfBug

**Comment by aveXcaesar** [comment]
@ICACLE 
I can't find the `Yaapii.Xml.Xambly.Tests.DirectiveCopyOfXmlDocument()` method. May be you forgot to reference a special brach?
