### ISSUE TITLE
Is it good if the .Xpath() Directives throws a exception if the given xpath is not aviable?

### ISSUE THREAD

**Issue by icaOBU** [icarus-consulting/Yaapii.Xambly#123]
### Expected Behavior

If the injected xpath in the .XPath() directive is not available in the applied XML document, the user is informed by a Exception

@icarus-consulting/dop  what do you think?
### Actual Behavior

No information to the user

**Comment by Meerownymous** [comment]
I dont think that would be good behaviour, because we often have cases where in case that nodes are not there xambly just has to do nothing. The validation of the xpath should be done somewhere else in the application, them.
