### ISSUE TITLE
Missing test for Multithreading

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Xambly#61]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
This test is implemented: https://github.com/icarus-consulting/Yaapii.Xembly/blob/7316280f92154eb434812e7d052147ab21f37cae/tests/Yaapii.Xml.Xembly.Tests/Directive/DirectivesTest.cs#L247

### Actual Behavior
Isnt 👎

**Comment by ICACLE** [comment]
The test locks the Directives object on building it on multiple threads, because of each directive command (`.Add()`) returns the Directives object. So the developer have to lock it to get thread safty.
The Xml() Method will now be calld in multiple threads, it works :+1:

**Comment by Meerownymous** [comment]
I think we need to do the following test: 
- make a FkDirective which sleeps for 100ms
- construct directives by using other Directives with FkDirective inside
- Start a Thread Generating Xml
- Start a second Thread which changes directives

And then check the output. Because in the current test the directives do not change.

But lets set that for later and see first, if we get problems.
