### ISSUE TITLE
Correct Test Namespaces

### ISSUE THREAD

**Issue by ICACLE** [icarus-consulting/Yaapii.Xambly#69]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior

Most Tests have the `namespace Yaapii.Xml.Xembly.Tests.Directive`
some have the `namespace Yaapii.Xml.Xembly.Directive.Tests`

I think to remeber we said the last one should be used, right?

### Actual Behavior

Mixed namespace
### Steps to reproduce the behavior

https://github.com/icarus-consulting/Yaapii.Xembly/blob/f0350ac1312451c27f32b0814cb2a713fba01bf1/tests/Yaapii.Xml.Xembly.Tests/Directive/DirectivesTest.cs#L14

https://github.com/icarus-consulting/Yaapii.Xembly/blob/f0350ac1312451c27f32b0814cb2a713fba01bf1/tests/Yaapii.Xml.Xembly.Tests/Directive/PopDirectiveTests.cs#L8

**Comment by Meerownymous** [comment]
Done
