### ISSUE TITLE
LowerXambler is missing in NuGet package 0.2.0

### ISSUE THREAD

**Issue by koeeenig** [icarus-consulting/Yaapii.Xambly#94]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
I can use the LowerXambler Decorator.

### Actual Behavior
Class in missing in NuGet Package Version 0.2.0.

### Steps to reproduce the behavior
Reference Xambly 0.2.0 and try to use the decorator class LowerXambler.

### Mention any other details that might be useful
I unziped the nuget package and investigated the Yaapii.Xml.Xambly.dll.
![image](https://user-images.githubusercontent.com/18014331/33871235-ed674950-df11-11e7-8e35-5471ef132c5a.png)
It looks like there is a LowerXambler class but it is even in a wrong namespace. Checked with the 
![image](https://user-images.githubusercontent.com/18014331/33871243-f58a61b2-df11-11e7-9a05-2b680281c70b.png)

If i look at the source code here on github for the tag 0.2.0 the LowerXambler class in missing. I think there went something wrong at renaming the project to Xambly.

**Comment by Meerownymous** [comment]
closed via #97
