### ISSUE TITLE
Version 0.3.0 is not published to Nuget.org

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Xambly#99]
### Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Expected Behavior
Nuget.org offers Xambly version 0.3.0

### Actual Behavior
Latest and only version on nuget.org is 0.2.0

**Comment by koeeenig** [comment]
fixed ... closing
